{Asset::css('bootstrap.css')}
{Asset::css('jquery-ui.css')}
{Asset::css('glayer.css')}
{Asset::css('jquery_notification.css')}
{Asset::css('app.css')}
{Asset::js('jquery-1.11.3.min.js')}
{Asset::js('jquery.cookie.min.js')}
{Asset::js('jquery-ui.min.js')}
{Asset::js('glayer.js')}
{Asset::js('jquery_notification_v.1.js')}